apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: klutch-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: klutch-test
      app.kubernetes.io/name: klutch-depoyment
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: klutch-test
        app.kubernetes.io/name: klutch-depoyment
    spec:
      containers:
      - image: rancher/hello-world:v0.1.2
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
