---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klutch-example-app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: klutch-example
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: klutch-example
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
        imagePullPolicy: IfNotPresent
        name: consumer
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 10Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    klutch.it/enabled: "1"
    klutch.it/scale-percentage-of-actual: "400"
  name: klutch-example-app
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: klutch-example-app
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Service
metadata:
  name: klutch-example-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: klutch-example
    app.kubernetes.io/name: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klutch-example-generator
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: klutch-example
      app.kubernetes.io/name: generator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: klutch-example
        app.kubernetes.io/name: generator
    spec:
      containers:
      - image: curlimages/curl:7.71.0
        imagePullPolicy: IfNotPresent
        name: generator
        args: ["sh", "-c", "while true; do curl http://klutch-example-app:8080/ConsumeCPU -s --data \"millicores=100&durationSec=120\" && sleep 125s; done"]
