apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    klutch.it/enabled: "1"
    klutch.it/scale-percentage-of-actual: "200"
  name: klutch-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: klutch-deployment
  targetCPUUtilizationPercentage: 70
