---
# Add this deployment and hpa to test scanning and reverting of 'orphaned' hpas
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: klutch-orphan-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: klutch-test-orphan
      app.kubernetes.io/name: klutch-depoyment
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: klutch-test-orphan
        app.kubernetes.io/name: klutch-depoyment
    spec:
      containers:
      - image: rancher/hello-world:v0.1.2
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    klutch.it/enabled: "1"
    klutch.it/scale-percentage-of-actual: "200"
    klutch.it/status: '{"originalMinReplicas": 2, "originalCurrentReplicas": 2, "appliedMinReplicas": 3, "appliedAt": 1588015000}'
  name: klutch-orphan-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: klutch-orphan-deployment
  targetCPUUtilizationPercentage: 70
