name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3

      # Based on: https://github.com/python-poetry/poetry/actions/runs/30094511/workflow
      - name: Configure Poetry
        run: |
          source $HOME/.poetry/env
          poetry config virtualenvs.in-project true

      - name: Configure pre-commit
        run: echo '::set-env name=PRE_COMMIT_HOME::.pre-commit-cache'

      - name: Set up Poetry cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-python-3.8-${{ hashFiles('**/poetry.lock') }}

      - name: Set up pre-commit cache
        uses: actions/cache@v1
        with:
          path: .pre-commit-cache
          key: pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install

      - name: Linting and tests
        run: poetry run pre-commit run --all-files
