name: CI/CD

on: [push, pull_request]

jobs:

  test:
    name: Run linting and tests
    runs-on: ubuntu-latest
    # Prevent from runing twice on PRs in same repo. So either run from push (same repo) or PR (fork)
    # See: https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/6
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached Poetry venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Configure pre-commit
        run: echo "PRE_COMMIT_HOME=.pre-commit-cache" >> $GITHUB_ENV

      - name: Set up pre-commit cache
        uses: actions/cache@v2
        with:
          path: .pre-commit-cache
          key: pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Linting and tests
        run: poetry run pre-commit run --all-files

  docker:
    # Note: Will be skipped together with test job if skipped by 'if' in test job.
    name: Build docker image
    runs-on: ubuntu-latest
    needs: test
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: tbeijen/klutch:test
          cache-from: type=registry,ref=tbeijen/klutch:latest
          cache-to: type=inline
