name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish docker image and chart
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Get tag
        id: tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tbeijen/klutch:${{ env.GIT_TAG }}
            tbeijen/klutch:latest
          cache-from: type=registry,ref=tbeijen/klutch:latest
          cache-to: type=inline

      - name: Update chart versions
        run: ./.github/scripts/set_version.sh

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
